Repository eclipse/xtext-web, pull requests merged in 2019-04, with the labels that each got.

#112 [eclipse/xtext#1423] Update Gradle Wrapper to Version 5.3.1
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: releng

#111 Remove IDEA since the support has been dropped
  gradle/manifest-gen.gradle
Labels: restructuring

#113 [eclipse/xtext#1424] Change default Jenkins
  README.md
  gradle/bootstrap-setup.gradle
  gradle/upstream-repositories.gradle
Labels: releng

#114 Use mavenCentral instead of jcenter to avoid sync delays and stability issues
  build.gradle
  gradle/bootstrap-setup.gradle
  gradle/upstream-repositories.gradle
Labels: releng

#115 replaced tf jenkins with ci.eclipse.org/xtext for lsp4j
  gradle/upstream-repositories.gradle
Labels: releng

#116 Hs issue 86
  build.gradle
  gradle/manifest-gen.gradle
  gradle/versions.gradle
  org.eclipse.xtext.web.servlet/build.gradle
  org.eclipse.xtext.web/build.gradle
  org.eclipse.xtext.xbase.web/build.gradle
Labels: releng

#119 [eclipse/xtext#1309] Provide Jenkinsfile for Eclipse CBI
  1-gradle-build.sh
  CBI.Jenkinsfile
  gradle/java-compiler-settings.gradle
Labels: releng

#118 Add option to build web samples langs with gradle #109
  Jenkinsfile
  build.gradle
  gradle/mwe2-workflows.gradle
  org.eclipse.xtext.web.example.entities/build.gradle
  org.eclipse.xtext.web.example.statemachine/build.gradle
Labels: releng

#121 [xtext-extras#403] Fixed regression in injector provider
  org.eclipse.xtext.web/src/test/xtext-gen/org/eclipse/xtext/web/example/statemachine/tests/StatemachineInjectorProvider.java
  org.eclipse.xtext.xbase.web/src/test/xtext-gen/org/eclipse/xtext/web/example/entities/tests/EntitiesInjectorProvider.java
Labels: bug

#124 Fix Web on CBI
  CBI.Jenkinsfile
  org.eclipse.xtext.web/build.gradle
Labels: releng
