Repository eclipse/xtext-web, pull requests merged in 2019-11, with the labels that each got.

#189 [eclipse/xtext#1573] Ensure that all plugins do have a ManifestBuilder
  gradle/eclipse-project-layout.gradle
Labels: releng

#191 [releng] Bootstrap against 2.20.0.M2
  gradle/versions.gradle
Labels: bot, releng

#193 added gradle properties
  gradle.properties
Labels: releng

#196 Align the Xtext Entities web example to the Domainmodel example.
  org.eclipse.xtext.web.example.entities/src/org/eclipse/xtext/web/example/entities/jvmmodel/EntitiesJvmModelHelper.xtend
  org.eclipse.xtext.web.example.entities/src/org/eclipse/xtext/web/example/entities/jvmmodel/EntitiesJvmModelInferrer.xtend
Labels: enhancement

#197 updated grgit gradle plugin to version 4.0.0
  build.gradle
Labels: releng

#200 [releng] Bootstrap against 2.20.0.M3
  gradle/versions.gradle
Labels: bot, releng
