Repository eclipse/xtext-web, pull requests merged in 2020-01, with the labels that each got.

#209 [releng] Bootstrap against 2.21.0.M1
  gradle/versions.gradle
Labels: bot, releng

#210 update grgit to 4.0.1
  build.gradle
Labels: releng

#206 [eclipse/xtext#1644] use java platform
  build.gradle
  gradle/versions.gradle
Labels: releng

#211 [eclipse/xtext#1595] Escape branch name for k8s label
  Jenkinsfile
Labels: releng

#215 [eclipse/xtext#1548] update bnd gradle plugin to 5.0.0 to avoid warnings with gradle 6.x
  gradle/versions.gradle
Labels: releng, technical_debt
