Repository eclipse/xtext-web, pull requests merged in 2020-10, with the labels that each got.

#260 update grgit
  build.gradle
Labels: releng

#261 updated mocha (sec fixes)
  org.eclipse.xtext.web/package-lock.json
  org.eclipse.xtext.web/package.json
Labels: releng

#263 [#262] update to jquery 3.5.1
  org.eclipse.xtext.web.example.jetty/build.gradle
  org.eclipse.xtext.web.example.jetty/src/main/webapp/ace-statemachine-resource-multi.html
  org.eclipse.xtext.web.example.jetty/src/main/webapp/ace-statemachine-resource.html
  org.eclipse.xtext.web.example.jetty/src/main/webapp/ace-statemachine-stateless.html
  org.eclipse.xtext.web.example.jetty/src/main/webapp/ace-statemachine-static-multi.html
  org.eclipse.xtext.web.example.jetty/src/main/webapp/ace-statemachine-static.html
  org.eclipse.xtext.web.example.jetty/src/main/webapp/codemirror-statemachine-resource-multi.html
  org.eclipse.xtext.web.example.jetty/src/main/webapp/codemirror-statemachine-resource.html
  org.eclipse.xtext.web.example.jetty/src/main/webapp/codemirror-statemachine-stateless.html
  org.eclipse.xtext.web.example.jetty/src/main/webapp/codemirror-statemachine-static-multi.html
  org.eclipse.xtext.web.example.jetty/src/main/webapp/codemirror-statemachine-static.html
  org.eclipse.xtext.web.example.jetty/src/main/webapp/index.html
  org.eclipse.xtext.web.example.jetty/src/main/webapp/orion-entities-resource.html
  org.eclipse.xtext.web.example.jetty/src/main/webapp/orion-entities-static.html
  org.eclipse.xtext.web.example.jetty/src/main/webapp/orion-statemachine-autogenerate.html
  org.eclipse.xtext.web.example.jetty/src/main/webapp/orion-statemachine-resource-multi.html
  org.eclipse.xtext.web.example.jetty/src/main/webapp/orion-statemachine-resource.html
  org.eclipse.xtext.web.example.jetty/src/main/webapp/orion-statemachine-stateless.html
  org.eclipse.xtext.web.example.jetty/src/main/webapp/orion-statemachine-static-multi.html
  org.eclipse.xtext.web.example.jetty/src/main/webapp/orion-statemachine-static.html
Labels: releng

#264 Download Orion via HTTPS
  org.eclipse.xtext.web.example.jetty/build.gradle
Labels: releng

#265 [releng] Bootstrap against 2.24.0.M1
  gradle/versions.gradle
Labels: bot, releng

#266 PrecomputedServiceRegistry has bogus locking
  org.eclipse.xtext.web/src/main/java/org/eclipse/xtext/web/server/model/PrecomputedServiceRegistry.java
Labels: bug, enhancement
