Repository eclipse/xtext-web, pull requests merged in 2020-05, with the labels that each got.

#233 [eclipse/xtext-core#1462] Regenerated languages
  org.eclipse.xtext.web.example.entities/src-gen/org/eclipse/xtext/web/example/entities/parser/antlr/internal/InternalEntities.g
  org.eclipse.xtext.web.example.entities/src-gen/org/eclipse/xtext/web/example/entities/parser/antlr/internal/InternalEntitiesParser.java
Labels: bug

#234 [releng] Bootstrap against 2.22.0.M2
  gradle/versions.gradle
Labels: bot, releng

#237 [releng] Bootstrap against 2.22.0.M3
  gradle/versions.gradle
Labels: bot, releng

#238 [eclipse/xtext#1769] Removed jnlp image name from pod template
  Jenkinsfile
Labels: releng
